#!/usr/bin/env bash
# installs haproxy on a new load balancer and setups the config to point to your webserver's IP address
apt-get -y update
apt-get -y install haproxy
echo "ENABLED=1" | tee -a /etc/default/haproxy
clear
echo "You must edit the /etc/haproxy/haproxy.cfg file manually to set ip address and hostname\n Press i to insert, modify file, then press <ESC_KEY>:x and press enter to save and exit\n"
mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sleep 2
echo -e "defaults\n\tmode http\n\ttimeout connect 5000\n\ttimeout client 10000\n\ttimeout server 10000\n\ttimeout http-request 100\n\nfrontend myfrontend\n\tbind :80\n\tdefault_backend myservers\n\nbackend myservers\n\tserver <HOSTNAME> <SERVER_IP>\n\tserver <HOSTNAME2> <SERVER_IP2>" | tee /etc/haproxy/haproxy.cfg
vi +/HOSTNAME /etc/haproxy/haproxy.cfg
service haproxy restart
