#!/usr/bin/env bash
# Installs needed software on new ubuntu 20+ machine

# Move to / directory
cd /
apt-get -y update
apt-get -y upgrade
# Install unzip and make utility
apt-get -y install unzip
apt-get -y install build-essential
apt-get -y install make

apt-get -y install valgrind
# Download and install stderred
wget https://github.com/sickill/stderred/archive/refs/heads/master.zip
unzip master.zip
cd stderred-master/
make
export LD_PRELOAD="/stderred/build/libstderred.so${LD_PRELOAD:+:$LD_PRELOAD}"
echo -e "export LD_PRELOAD=\"/stderred/build/libstderred.so\${LD_PRELOAD:+:\$LD_PRELOAD}\"" | tee -a ~/.bashrc
# Check Versions
sleep 2
apt-get -y update
apt-get -y upgrade
unzip --version
make --version
valgrind --version
find -q
