#!/usr/bin/env bash
# Configures python3 for a machine

cd ~
apt-get -y update
apt-get -y upgrade
apt-get install -y software-properties-common
add-apt-repository -y ppa:deadsnakes/ppa
apt-get -y update
apt-get install -y python3.10
wget https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py
pip install --upgrade pip
apt install -y libssl-dev libffi-dev python3-dev
apt-get -y install pycodestyle
rm get-pip.py
